- hosts: all
  gather_facts: yes
  become: yes

  tasks:

    - name: yum install yum-utils device-mapper-persistent-data lvm2
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: shell install docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: yum install docker-ce docker-ce-cli containerd.io
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io


    - name: yum install epel-release
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - epel-release

    - name: yum install python-pip
      yum:
        lock_timeout: 60 
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - python-pip

    - name: pip upgrade
      shell: pip install pip --upgrade

    - name: pip install docker
      shell: pip install docker --ignore-installed  requests
      ignore_errors: True

    - name: pip install  docker-compose
      shell: pip install docker-compose --ignore-installed  requests
      ignore_errors: True

    - name: systemctl docker enable start
      systemd:
        state: started
        enabled: yes
        name: docker

    - name: yum install ansible
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - ansible

    - name: yum git2 repository install
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: latest

    - name: yum install perl-TermReadKey perl-Error libsecret
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - perl-TermReadKey
        - perl-Error
        - libsecret

    - name: yum install git2u
      yum:
        lock_timeout: 60
        enablerepo: ius
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - git2u

    - name: get install script by npm
      get_url:
        url: https://rpm.nodesource.com/setup_8.x
        dest: /root/setup_8.x.sh
    - name: chenge mode insgtall script
      file:
        path: /root/setup_8.x.sh
        mode: '0755'
    - name: install npm
      shell: /root/setup_8.x.sh

    - name: yum install nodejs
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - nodejs

    - name: yum install gcc-c++ make
      yum:
        lock_timeout: 60
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - gcc-c++
        - make

    - name: remove ansible awx dir
      shell: rm -rf /root/awx

    - name: make ansible awx dir
      shell: rm -rf /root/awx

    - name: git get ansible awx
      git:
        repo: 'https://github.com/ansible/awx'
        dest: /root/awx

    - name: remote yum update all?
      pause: prompt="remote server yum update all? (y/n)"
      register: yn

    - name: yum all update
      yum:
        lock_timeout: 60
        name: '*'
        state: latest
      when:  yn.user_input ==  'y'

    - name: remote server reboot?
      pause: prompt="remote server reboot ok? (y/n)"
      register: yn

    - name: machine reboot
      reboot:
        reboot_timeout: 600
      when:  yn.user_input ==  'y'

    - name: remote machi reboot wait
      wait_for_connection:
        connect_timeout: 180
        sleep: 5
        delay: 5
        timeout: 180
      when:  yn.user_input ==  'y'

    - name: please login to the remote host
      debug:
        msg: " Please login to ssh {{ inventory_hostname }} "
    - name: Change to Superuser
      debug:
        msg: " run 'sudo su - '"
    - name: Change dir
      debug:
        msg: " run 'cd /root/awx/installer'"
    - name: run ansible installer
      debug:
        msg: " run 'ansible-playbook -i inventory install.yml'"

